#target : Dependencies
#<TAB>commands

Build : project_main.c ControlHomeAppliances.c 
        gcc project_main.c ControlHomeAppliances.c ControlHomeAppliances.out
Run : ControlHomeAppliances.out
	   ./ControlhomeAppliances.out
Clean : 
		rm -rf * .o *.out *.i *.s
